fixtures:
  repositories:
    concat: https://github.com/puppetlabs/puppetlabs-concat
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    cron_crore: 'https://github.com/puppetlabs/puppetlabs-cron_core'
  symlinks:
    reprepro: "#{source_dir}"
